//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalAnalysis.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignalAnalysis.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by {0}.
        /// </summary>
        internal static string strAboutCompanyName {
            get {
                return ResourceManager.GetString("strAboutCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright {0}.
        /// </summary>
        internal static string strAboutCopyright {
            get {
                return ResourceManager.GetString("strAboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis tool featuring basic descriptive statistics, FFT (fast Fourier transform), fractal dimension, differentiation, integration, and entropy for signals (elux files as well as generic ones).
        ///
        ///No commercial use allowed whatsoever. Contact the author for any inquiries.
        ///
        ///If you find this software useful, please consider supporting it!.
        /// </summary>
        internal static string strAboutDescription {
            get {
                return ResourceManager.GetString("strAboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name: {0}.
        /// </summary>
        internal static string strAboutProductName {
            get {
                return ResourceManager.GetString("strAboutProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string strAboutVersion {
            get {
                return ResourceManager.GetString("strAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Accept.
        /// </summary>
        internal static string strBtnAccept {
            get {
                return ResourceManager.GetString("strBtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string strBtnCancel {
            get {
                return ResourceManager.GetString("strBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data.
        /// </summary>
        internal static string strBtnData {
            get {
                return ResourceManager.GetString("strBtnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export.
        /// </summary>
        internal static string strBtnExport {
            get {
                return ResourceManager.GetString("strBtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string strBtnReset {
            get {
                return ResourceManager.GetString("strBtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string strBtnSettings {
            get {
                return ResourceManager.GetString("strBtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute the absolute-value integral?.
        /// </summary>
        internal static string strChkAbsoluteIntegral {
            get {
                return ResourceManager.GetString("strChkAbsoluteIntegral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box plot.
        /// </summary>
        internal static string strChkBoxplot {
            get {
                return ResourceManager.GetString("strChkBoxplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute numerical differentiation?.
        /// </summary>
        internal static string strChkComputeDerivative {
            get {
                return ResourceManager.GetString("strChkComputeDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute numerical integration?.
        /// </summary>
        internal static string strChkComputeIntegration {
            get {
                return ResourceManager.GetString("strChkComputeIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show plots&apos; crosshair.
        /// </summary>
        internal static string strChkCrossHair {
            get {
                return ResourceManager.GetString("strChkCrossHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative fractal dimension.
        /// </summary>
        internal static string strChkCumulative {
            get {
                return ResourceManager.GetString("strChkCumulative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember open/save dialog previous path.
        /// </summary>
        internal static string strChkDlgPath {
            get {
                return ResourceManager.GetString("strChkDlgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy (approximate and sample).
        /// </summary>
        internal static string strChkEntropy {
            get {
                return ResourceManager.GetString("strChkEntropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export derivative data?.
        /// </summary>
        internal static string strChkExportDerivative {
            get {
                return ResourceManager.GetString("strChkExportDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export numerical integration?.
        /// </summary>
        internal static string strChkExportIntegration {
            get {
                return ResourceManager.GetString("strChkExportIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power (dB).
        /// </summary>
        internal static string strChkPower {
            get {
                return ResourceManager.GetString("strChkPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember window position and size on startup.
        /// </summary>
        internal static string strChkWindowPos {
            get {
                return ResourceManager.GetString("strChkWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward one-point difference, Forward one-point difference, Central three-point difference, Central five-point difference, Central seven-point difference, Central nine-point difference, Savitzky–Golay linear three point, Savitzky–Golay linear five point, Savitzky–Golay linear seven point, Savitzky–Golay linear nine point, Savitzky–Golay cubic five point, Savitzky–Golay cubic seven point, Savitzky–Golay cubic nine point.
        /// </summary>
        internal static string strDifferentiationAlgorithms {
            get {
                return ResourceManager.GetString("strDifferentiationAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset all fields
        ///to their default values?.
        /// </summary>
        internal static string strDlgReset {
            get {
                return ResourceManager.GetString("strDlgReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings?.
        /// </summary>
        internal static string strDlgResetTitle {
            get {
                return ResourceManager.GetString("strDlgResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brute force, Monte-Carlo.
        /// </summary>
        internal static string strEntropyAlgorithms {
            get {
                return ResourceManager.GetString("strEntropyAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings file.
        ///
        ///{0}
        ///
        ///Default values will be used instead..
        /// </summary>
        internal static string strErrorDeserialize {
            get {
                return ResourceManager.GetString("strErrorDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strErrorDeserializeTitle {
            get {
                return ResourceManager.GetString("strErrorDeserializeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErgoLux data.
        /// </summary>
        internal static string strFileHeader00 {
            get {
                return ResourceManager.GetString("strFileHeader00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignalAnalysis data.
        /// </summary>
        internal static string strFileHeader01 {
            get {
                return ResourceManager.GetString("strFileHeader01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string strFileHeader02 {
            get {
                return ResourceManager.GetString("strFileHeader02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        internal static string strFileHeader03 {
            get {
                return ResourceManager.GetString("strFileHeader03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total measuring time.
        /// </summary>
        internal static string strFileHeader04 {
            get {
                return ResourceManager.GetString("strFileHeader04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of data points.
        /// </summary>
        internal static string strFileHeader05 {
            get {
                return ResourceManager.GetString("strFileHeader05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling frequency.
        /// </summary>
        internal static string strFileHeader06 {
            get {
                return ResourceManager.GetString("strFileHeader06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string strFileHeader07 {
            get {
                return ResourceManager.GetString("strFileHeader07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string strFileHeader08 {
            get {
                return ResourceManager.GetString("strFileHeader08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string strFileHeader09 {
            get {
                return ResourceManager.GetString("strFileHeader09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal dimension.
        /// </summary>
        internal static string strFileHeader10 {
            get {
                return ResourceManager.GetString("strFileHeader10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal variance.
        /// </summary>
        internal static string strFileHeader11 {
            get {
                return ResourceManager.GetString("strFileHeader11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximate entropy.
        /// </summary>
        internal static string strFileHeader12 {
            get {
                return ResourceManager.GetString("strFileHeader12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample entropy.
        /// </summary>
        internal static string strFileHeader13 {
            get {
                return ResourceManager.GetString("strFileHeader13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shannon entropy.
        /// </summary>
        internal static string strFileHeader14 {
            get {
                return ResourceManager.GetString("strFileHeader14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy bit.
        /// </summary>
        internal static string strFileHeader15 {
            get {
                return ResourceManager.GetString("strFileHeader15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal entropy.
        /// </summary>
        internal static string strFileHeader16 {
            get {
                return ResourceManager.GetString("strFileHeader16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of data series.
        /// </summary>
        internal static string strFileHeader17 {
            get {
                return ResourceManager.GetString("strFileHeader17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sensors.
        /// </summary>
        internal static string strFileHeader18 {
            get {
                return ResourceManager.GetString("strFileHeader18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing an empty line..
        /// </summary>
        internal static string strFileHeader19 {
            get {
                return ResourceManager.GetString("strFileHeader19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing column headers (series names)..
        /// </summary>
        internal static string strFileHeader20 {
            get {
                return ResourceManager.GetString("strFileHeader20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string strFileHeader21 {
            get {
                return ResourceManager.GetString("strFileHeader21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days, day, days.
        /// </summary>
        internal static string strFileHeader22 {
            get {
                return ResourceManager.GetString("strFileHeader22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours, hour, hours.
        /// </summary>
        internal static string strFileHeader23 {
            get {
                return ResourceManager.GetString("strFileHeader23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes, minute, minutes.
        /// </summary>
        internal static string strFileHeader24 {
            get {
                return ResourceManager.GetString("strFileHeader24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds, second, seconds.
        /// </summary>
        internal static string strFileHeader25 {
            get {
                return ResourceManager.GetString("strFileHeader25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string strFileHeader26 {
            get {
                return ResourceManager.GetString("strFileHeader26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds, millisecond, milliseconds.
        /// </summary>
        internal static string strFileHeader27 {
            get {
                return ResourceManager.GetString("strFileHeader27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivative.
        /// </summary>
        internal static string strFileHeader28 {
            get {
                return ResourceManager.GetString("strFileHeader28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differentiation algorithm.
        /// </summary>
        internal static string strFileHeader29 {
            get {
                return ResourceManager.GetString("strFileHeader29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration algorithm.
        /// </summary>
        internal static string strFileHeader30 {
            get {
                return ResourceManager.GetString("strFileHeader30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral value.
        /// </summary>
        internal static string strFileHeader31 {
            get {
                return ResourceManager.GetString("strFileHeader31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance.
        /// </summary>
        internal static string strFileHeader32 {
            get {
                return ResourceManager.GetString("strFileHeader32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box plot lower limit.
        /// </summary>
        internal static string strFileHeader33 {
            get {
                return ResourceManager.GetString("strFileHeader33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box plot upper limit.
        /// </summary>
        internal static string strFileHeader34 {
            get {
                return ResourceManager.GetString("strFileHeader34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartile 1 (25%).
        /// </summary>
        internal static string strFileHeader35 {
            get {
                return ResourceManager.GetString("strFileHeader35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartile 2 (50%).
        /// </summary>
        internal static string strFileHeader36 {
            get {
                return ResourceManager.GetString("strFileHeader36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartile 3 (75%).
        /// </summary>
        internal static string strFileHeader37 {
            get {
                return ResourceManager.GetString("strFileHeader37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shannon / Ideal.
        /// </summary>
        internal static string strFileHeader38 {
            get {
                return ResourceManager.GetString("strFileHeader38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy algorithm.
        /// </summary>
        internal static string strFileHeader39 {
            get {
                return ResourceManager.GetString("strFileHeader39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy tolerance factor.
        /// </summary>
        internal static string strFileHeader40 {
            get {
                return ResourceManager.GetString("strFileHeader40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy Embedding dimension.
        /// </summary>
        internal static string strFileHeader41 {
            get {
                return ResourceManager.GetString("strFileHeader41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string strFileHeaderColon {
            get {
                return ResourceManager.GetString("strFileHeaderColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;{0}&apos; is mis-formatted..
        /// </summary>
        internal static string strFileHeaderSection {
            get {
                return ResourceManager.GetString("strFileHeaderSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select culture.
        /// </summary>
        internal static string strFrmLanguage {
            get {
                return ResourceManager.GetString("strFrmLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string strFrmSettings {
            get {
                return ResourceManager.GetString("strFrmSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal analysis.
        /// </summary>
        internal static string strFrmTitle {
            get {
                return ResourceManager.GetString("strFrmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string strFrmTitleUnion {
            get {
                return ResourceManager.GetString("strFrmTitleUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finite difference algorithms.
        /// </summary>
        internal static string strGrpAlgorithms {
            get {
                return ResourceManager.GetString("strGrpAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abscissa axis.
        /// </summary>
        internal static string strGrpAxis {
            get {
                return ResourceManager.GetString("strGrpAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI and data format.
        /// </summary>
        internal static string strGrpCulture {
            get {
                return ResourceManager.GetString("strGrpCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT points.
        /// </summary>
        internal static string strGrpFFT {
            get {
                return ResourceManager.GetString("strGrpFFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-point rule, Mid-point rule, Right-point rule, Trapezoid rule, Simpson&apos;s 1/3 rule, Simpson&apos;s 3/8 rule, Simpson&apos;s composite rule, Romberg&apos;s method.
        /// </summary>
        internal static string strIntegrationAlgorithms {
            get {
                return ResourceManager.GetString("strIntegrationAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data-file path.
        /// </summary>
        internal static string strLblData {
            get {
                return ResourceManager.GetString("strLblData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric data-formatting string.
        /// </summary>
        internal static string strLblDataFormat {
            get {
                return ResourceManager.GetString("strLblDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array index end (max {0}).
        /// </summary>
        internal static string strLblEnd {
            get {
                return ResourceManager.GetString("strLblEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy algorithms.
        /// </summary>
        internal static string strLblEntropy {
            get {
                return ResourceManager.GetString("strLblEntropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedding dimension.
        /// </summary>
        internal static string strLblFactorM {
            get {
                return ResourceManager.GetString("strLblFactorM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance factor.
        /// </summary>
        internal static string strLblFactorR {
            get {
                return ResourceManager.GetString("strLblFactorR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrature algorithms.
        /// </summary>
        internal static string strLblIntegration {
            get {
                return ResourceManager.GetString("strLblIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select series.
        /// </summary>
        internal static string strLblSeries {
            get {
                return ResourceManager.GetString("strLblSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array index start.
        /// </summary>
        internal static string strLblStart {
            get {
                return ResourceManager.GetString("strLblStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string strLblWindow {
            get {
                return ResourceManager.GetString("strLblWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error while computing numerical differentiation.
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorDerivative {
            get {
                return ResourceManager.GetString("strMsgBoxErrorDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differentiation error.
        /// </summary>
        internal static string strMsgBoxErrorDerivativeTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorDerivativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error while computing descriptive statistics values.
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorDescriptiveStats {
            get {
                return ResourceManager.GetString("strMsgBoxErrorDescriptiveStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics error.
        /// </summary>
        internal static string strMsgBoxErrorDescriptiveStatsTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorDescriptiveStatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error while computing entropy values.
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorEntropy {
            get {
                return ResourceManager.GetString("strMsgBoxErrorEntropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy error.
        /// </summary>
        internal static string strMsgBoxErrorEntropyTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorEntropyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error while computing the FFT.
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorFFT {
            get {
                return ResourceManager.GetString("strMsgBoxErrorFFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT error.
        /// </summary>
        internal static string strMsgBoxErrorFFTTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorFFTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error while computing the fractal dimension.
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorFractal {
            get {
                return ResourceManager.GetString("strMsgBoxErrorFractal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal error.
        /// </summary>
        internal static string strMsgBoxErrorFractalTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorFractalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error happened while opening data file.
        ///Please try again later or contact the software engineer.
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorOpenData {
            get {
                return ResourceManager.GetString("strMsgBoxErrorOpenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening data.
        /// </summary>
        internal static string strMsgBoxErrorOpenDataTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorOpenDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error happened while saving data file.
        ///Please try again later or contact the software engineer.
        ///{0}.
        /// </summary>
        internal static string strMsgBoxErrorSaveData {
            get {
                return ResourceManager.GetString("strMsgBoxErrorSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving data.
        /// </summary>
        internal static string strMsgBoxErrorSaveDataTitle {
            get {
                return ResourceManager.GetString("strMsgBoxErrorSaveDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit
        ///the application?.
        /// </summary>
        internal static string strMsgBoxExit {
            get {
                return ResourceManager.GetString("strMsgBoxExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string strMsgBoxExitTitle {
            get {
                return ResourceManager.GetString("strMsgBoxExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error in &apos;InitializeDataArrays&apos;.
        ///{0}.
        /// </summary>
        internal static string strMsgBoxInitArray {
            get {
                return ResourceManager.GetString("strMsgBoxInitArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strMsgBoxInitArrayTitle {
            get {
                return ResourceManager.GetString("strMsgBoxInitArrayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data available to be saved..
        /// </summary>
        internal static string strMsgBoxNoData {
            get {
                return ResourceManager.GetString("strMsgBoxNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string strMsgBoxNoDataTitle {
            get {
                return ResourceManager.GetString("strMsgBoxNoDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been successfully saved to disk..
        /// </summary>
        internal static string strMsgBoxOKSaveData {
            get {
                return ResourceManager.GetString("strMsgBoxOKSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved.
        /// </summary>
        internal static string strMsgBoxOKSaveDataTitle {
            get {
                return ResourceManager.GetString("strMsgBoxOKSaveDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical differentiation has been stopped..
        /// </summary>
        internal static string strMsgBoxTaskDerivativeCancel {
            get {
                return ResourceManager.GetString("strMsgBoxTaskDerivativeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string strMsgBoxTaskDerivativeCancelTitle {
            get {
                return ResourceManager.GetString("strMsgBoxTaskDerivativeCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy computation has been stopped..
        /// </summary>
        internal static string strMsgBoxTaskEntropyCancel {
            get {
                return ResourceManager.GetString("strMsgBoxTaskEntropyCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string strMsgBoxTaskEntropyCancelTitle {
            get {
                return ResourceManager.GetString("strMsgBoxTaskEntropyCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computation of the Hausdorff-Besicovitch fractal
        ///dimension has been stopped..
        /// </summary>
        internal static string strMsgBoxTaskFractalCancel {
            get {
                return ResourceManager.GetString("strMsgBoxTaskFractalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string strMsgBoxTaskFractalCancelTitle {
            get {
                return ResourceManager.GetString("strMsgBoxTaskFractalCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErgoLux files (*.elux)|*.elux|SignalAnalysis files (*.sig)|*.sig|Text files (*.txt)|*.txt|Binary files (*.bin)|*.bin|All files (*.*)|*.*.
        /// </summary>
        internal static string strOpenDlgFilter {
            get {
                return ResourceManager.GetString("strOpenDlgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open data file.
        /// </summary>
        internal static string strOpenDlgTitle {
            get {
                return ResourceManager.GetString("strOpenDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed signal.
        /// </summary>
        internal static string strPlotAppliedTitle {
            get {
                return ResourceManager.GetString("strPlotAppliedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotAppliedXLabel {
            get {
                return ResourceManager.GetString("strPlotAppliedXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        internal static string strPlotAppliedYLabel {
            get {
                return ResourceManager.GetString("strPlotAppliedYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box plot.
        /// </summary>
        internal static string strPlotBoxPlotTitle {
            get {
                return ResourceManager.GetString("strPlotBoxPlotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        internal static string strPlotBoxplotYLabel {
            get {
                return ResourceManager.GetString("strPlotBoxplotYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivative.
        /// </summary>
        internal static string strPlotDerivativeTitle {
            get {
                return ResourceManager.GetString("strPlotDerivativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotDerivativeXLabel {
            get {
                return ResourceManager.GetString("strPlotDerivativeXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude / sec.
        /// </summary>
        internal static string strPlotDerivativeYLabel1 {
            get {
                return ResourceManager.GetString("strPlotDerivativeYLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        internal static string strPlotDerivativeYLabel2 {
            get {
                return ResourceManager.GetString("strPlotDerivativeYLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Fourier transform.
        /// </summary>
        internal static string strPlotFFTTitle {
            get {
                return ResourceManager.GetString("strPlotFFTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (Hz).
        /// </summary>
        internal static string strPlotFFTXLabel {
            get {
                return ResourceManager.GetString("strPlotFFTXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnitude (RMS²).
        /// </summary>
        internal static string strPlotFFTYLabelMag {
            get {
                return ResourceManager.GetString("strPlotFFTYLabelMag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power (dB).
        /// </summary>
        internal static string strPlotFFTYLabelPow {
            get {
                return ResourceManager.GetString("strPlotFFTYLabelPow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal dimension (H).
        /// </summary>
        internal static string strPlotFractalDisributionXLabel {
            get {
                return ResourceManager.GetString("strPlotFractalDisributionXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability.
        /// </summary>
        internal static string strPlotFractalDisributionYLabel {
            get {
                return ResourceManager.GetString("strPlotFractalDisributionYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal dimension distribution.
        /// </summary>
        internal static string strPlotFractalDistributionTitle {
            get {
                return ResourceManager.GetString("strPlotFractalDistributionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal dimension.
        /// </summary>
        internal static string strPlotFractalTitle1 {
            get {
                return ResourceManager.GetString("strPlotFractalTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (cumulative).
        /// </summary>
        internal static string strPlotFractalTitle2 {
            get {
                return ResourceManager.GetString("strPlotFractalTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotFractalXLabel {
            get {
                return ResourceManager.GetString("strPlotFractalXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension (H).
        /// </summary>
        internal static string strPlotFractalYLabel {
            get {
                return ResourceManager.GetString("strPlotFractalYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input signal.
        /// </summary>
        internal static string strPlotOriginalTitle {
            get {
                return ResourceManager.GetString("strPlotOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotOriginalXLabel {
            get {
                return ResourceManager.GetString("strPlotOriginalXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        internal static string strPlotOriginalYLabel {
            get {
                return ResourceManager.GetString("strPlotOriginalYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} window.
        /// </summary>
        internal static string strPlotWindowTitle {
            get {
                return ResourceManager.GetString("strPlotWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotWindowXLabel {
            get {
                return ResourceManager.GetString("strPlotWindowXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        internal static string strPlotWindowYLabel {
            get {
                return ResourceManager.GetString("strPlotWindowYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current culture formatting.
        /// </summary>
        internal static string strRadCurrentCulture {
            get {
                return ResourceManager.GetString("strRadCurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant culture formatting.
        /// </summary>
        internal static string strRadInvariantCulture {
            get {
                return ResourceManager.GetString("strRadInvariantCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data points.
        /// </summary>
        internal static string strRadPoints {
            get {
                return ResourceManager.GetString("strRadPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round down (trim).
        /// </summary>
        internal static string strRadRoundDown {
            get {
                return ResourceManager.GetString("strRadRoundDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round up (add zeros).
        /// </summary>
        internal static string strRadRoundUp {
            get {
                return ResourceManager.GetString("strRadRoundUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string strRadSeconds {
            get {
                return ResourceManager.GetString("strRadSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        internal static string strRadTime {
            get {
                return ResourceManager.GetString("strRadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select culture.
        /// </summary>
        internal static string strRadUserCulture {
            get {
                return ResourceManager.GetString("strRadUserCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read data from file.
        ///{0}.
        /// </summary>
        internal static string strReadDataError {
            get {
                return ResourceManager.GetString("strReadDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The culture identifier string name is not valid.
        ///{0}.
        /// </summary>
        internal static string strReadDataErrorCulture {
            get {
                return ResourceManager.GetString("strReadDataErrorCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture name error.
        /// </summary>
        internal static string strReadDataErrorCultureTitle {
            get {
                return ResourceManager.GetString("strReadDataErrorCultureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid numeric value: {0}.
        /// </summary>
        internal static string strReadDataErrorNumber {
            get {
                return ResourceManager.GetString("strReadDataErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing data.
        /// </summary>
        internal static string strReadDataErrorNumberTitle {
            get {
                return ResourceManager.GetString("strReadDataErrorNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strReadDataErrorTitle {
            get {
                return ResourceManager.GetString("strReadDataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read data from a {0} file..
        /// </summary>
        internal static string strReadNotimplementedError {
            get {
                return ResourceManager.GetString("strReadNotimplementedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented.
        /// </summary>
        internal static string strReadNotimplementedErrorTitle {
            get {
                return ResourceManager.GetString("strReadNotimplementedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file (*.txt)|*.txt|SignalAnalysis file (*.sig)|*.sig|Binary file (*.bin)|*.bin|Results file (*.results)|*.results|All files (*.*)|*.*.
        /// </summary>
        internal static string strSaveDlgFilter {
            get {
                return ResourceManager.GetString("strSaveDlgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data file.
        /// </summary>
        internal static string strSaveDlgTitle {
            get {
                return ResourceManager.GetString("strSaveDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show plot&apos;s crosshair mode.
        /// </summary>
        internal static string strStatusTipCrossHair {
            get {
                return ResourceManager.GetString("strStatusTipCrossHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical differentiation.
        /// </summary>
        internal static string strStatusTipDerivative {
            get {
                return ResourceManager.GetString("strStatusTipDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute the approximate and sample entropy.
        /// </summary>
        internal static string strStatusTipEntropy {
            get {
                return ResourceManager.GetString("strStatusTipEntropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute the cumulative fractal dimension (CPU intensive).
        /// </summary>
        internal static string strStatusTipFractal {
            get {
                return ResourceManager.GetString("strStatusTipFractal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical integration.
        /// </summary>
        internal static string strStatusTipIntegration {
            get {
                return ResourceManager.GetString("strStatusTipIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot either FFT power spectra(dB) or magnitude.
        /// </summary>
        internal static string strStatusTipPower {
            get {
                return ResourceManager.GetString("strStatusTipPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differentiation.
        /// </summary>
        internal static string strTabDerivative {
            get {
                return ResourceManager.GetString("strTabDerivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy.
        /// </summary>
        internal static string strTabEntropy {
            get {
                return ResourceManager.GetString("strTabEntropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        internal static string strTabGUI {
            get {
                return ResourceManager.GetString("strTabGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        internal static string strTabIntegration {
            get {
                return ResourceManager.GetString("strTabIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plotting.
        /// </summary>
        internal static string strTabPlot {
            get {
                return ResourceManager.GetString("strTabPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string strToolStripAbout {
            get {
                return ResourceManager.GetString("strToolStripAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string strToolStripExit {
            get {
                return ResourceManager.GetString("strToolStripExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string strToolStripExport {
            get {
                return ResourceManager.GetString("strToolStripExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string strToolStripOpen {
            get {
                return ResourceManager.GetString("strToolStripOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string strToolStripSettings {
            get {
                return ResourceManager.GetString("strToolStripSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this software.
        /// </summary>
        internal static string strToolTipAbout {
            get {
                return ResourceManager.GetString("strToolTipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data series.
        /// </summary>
        internal static string strToolTipCboSeries {
            get {
                return ResourceManager.GetString("strToolTipCboSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select FFT window.
        /// </summary>
        internal static string strToolTipCboWindows {
            get {
                return ResourceManager.GetString("strToolTipCboWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        internal static string strToolTipExit {
            get {
                return ResourceManager.GetString("strToolTipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data and data analysis.
        /// </summary>
        internal static string strToolTipExport {
            get {
                return ResourceManager.GetString("strToolTipExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open data file from disk.
        /// </summary>
        internal static string strToolTipOpen {
            get {
                return ResourceManager.GetString("strToolTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for plots, data, and UI.
        /// </summary>
        internal static string strToolTipSettings {
            get {
                return ResourceManager.GetString("strToolTipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface language.
        /// </summary>
        internal static string strToolTipUILanguage {
            get {
                return ResourceManager.GetString("strToolTipUILanguage", resourceCulture);
            }
        }
    }
}
