//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalAnalysis.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignalAnalysis.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Accept.
        /// </summary>
        internal static string strBtnAccept {
            get {
                return ResourceManager.GetString("strBtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string strBtnCancel {
            get {
                return ResourceManager.GetString("strBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data.
        /// </summary>
        internal static string strBtnData {
            get {
                return ResourceManager.GetString("strBtnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export.
        /// </summary>
        internal static string strBtnExport {
            get {
                return ResourceManager.GetString("strBtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string strBtnReset {
            get {
                return ResourceManager.GetString("strBtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string strBtnSettings {
            get {
                return ResourceManager.GetString("strBtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show plots&apos; crosshair.
        /// </summary>
        internal static string strChkCrossHair {
            get {
                return ResourceManager.GetString("strChkCrossHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative fractal dimension.
        /// </summary>
        internal static string strChkCumulative {
            get {
                return ResourceManager.GetString("strChkCumulative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember open/save dialog previous path.
        /// </summary>
        internal static string strChkDlgPath {
            get {
                return ResourceManager.GetString("strChkDlgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy (approximate &amp;&amp; sample).
        /// </summary>
        internal static string strChkEntropy {
            get {
                return ResourceManager.GetString("strChkEntropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power (dB).
        /// </summary>
        internal static string strChkPower {
            get {
                return ResourceManager.GetString("strChkPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset all fields
        ///to their default values?.
        /// </summary>
        internal static string strDlgReset {
            get {
                return ResourceManager.GetString("strDlgReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings?.
        /// </summary>
        internal static string strDlgResetTitle {
            get {
                return ResourceManager.GetString("strDlgResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;ErgoLux data&apos; is mis-formatted..
        /// </summary>
        internal static string strELuxHeader01 {
            get {
                return ResourceManager.GetString("strELuxHeader01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;Start time&apos; is mis-formatted..
        /// </summary>
        internal static string strELuxHeader02 {
            get {
                return ResourceManager.GetString("strELuxHeader02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;End time&apos; is mis-formatted..
        /// </summary>
        internal static string strELuxHeader03 {
            get {
                return ResourceManager.GetString("strELuxHeader03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;Total measuring time&apos; is mis-formatted..
        /// </summary>
        internal static string strELuxHeader04 {
            get {
                return ResourceManager.GetString("strELuxHeader04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;Number of sensors&apos; is mis-formatted..
        /// </summary>
        internal static string strELuxHeader05 {
            get {
                return ResourceManager.GetString("strELuxHeader05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;Number of data points&apos; is mis-formatted..
        /// </summary>
        internal static string strELuxHeader06 {
            get {
                return ResourceManager.GetString("strELuxHeader06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section &apos;Sampling frequency&apos; is mis-formatted..
        /// </summary>
        internal static string strELuxHeader07 {
            get {
                return ResourceManager.GetString("strELuxHeader07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing an empty line..
        /// </summary>
        internal static string strELuxHeader08 {
            get {
                return ResourceManager.GetString("strELuxHeader08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing column headers (series names)..
        /// </summary>
        internal static string strELuxHeader09 {
            get {
                return ResourceManager.GetString("strELuxHeader09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings file.
        ///
        ///{0}
        ///
        ///Default values will be used instead..
        /// </summary>
        internal static string strErrorDeserialize {
            get {
                return ResourceManager.GetString("strErrorDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strErrorDeserializeTitle {
            get {
                return ResourceManager.GetString("strErrorDeserializeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string strFrmSettings {
            get {
                return ResourceManager.GetString("strFrmSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal analysis.
        /// </summary>
        internal static string strFrmTitle {
            get {
                return ResourceManager.GetString("strFrmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abscissa axis.
        /// </summary>
        internal static string strGrpAxis {
            get {
                return ResourceManager.GetString("strGrpAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI and data format.
        /// </summary>
        internal static string strGrpCulture {
            get {
                return ResourceManager.GetString("strGrpCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data-file path.
        /// </summary>
        internal static string strLblData {
            get {
                return ResourceManager.GetString("strLblData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric data-formatting string.
        /// </summary>
        internal static string strLblDataFormat {
            get {
                return ResourceManager.GetString("strLblDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array index end.
        /// </summary>
        internal static string strLblEnd {
            get {
                return ResourceManager.GetString("strLblEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select series.
        /// </summary>
        internal static string strLblSeries {
            get {
                return ResourceManager.GetString("strLblSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array index start.
        /// </summary>
        internal static string strLblStart {
            get {
                return ResourceManager.GetString("strLblStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string strLblWindow {
            get {
                return ResourceManager.GetString("strLblWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string strMsgBoxExit {
            get {
                return ResourceManager.GetString("strMsgBoxExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit
        ///the application?.
        /// </summary>
        internal static string strMsgBoxExitTitle {
            get {
                return ResourceManager.GetString("strMsgBoxExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error in &apos;InitializeDataArrays&apos;.
        ///{0}.
        /// </summary>
        internal static string strMsgBoxInitArray {
            get {
                return ResourceManager.GetString("strMsgBoxInitArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strMsgBoxInitArrayTitle {
            get {
                return ResourceManager.GetString("strMsgBoxInitArrayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computation of the Hausdorff-Besicovitch fractal
        ///dimension has been stopped..
        /// </summary>
        internal static string strMsgBoxTaskCancel {
            get {
                return ResourceManager.GetString("strMsgBoxTaskCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string strMsgBoxTaskCancelTitle {
            get {
                return ResourceManager.GetString("strMsgBoxTaskCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed signal.
        /// </summary>
        internal static string strPlotAppliedTitle {
            get {
                return ResourceManager.GetString("strPlotAppliedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotAppliedXLabel {
            get {
                return ResourceManager.GetString("strPlotAppliedXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        internal static string strPlotAppliedYLabel {
            get {
                return ResourceManager.GetString("strPlotAppliedYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Fourier transform.
        /// </summary>
        internal static string strPlotFFTTitle {
            get {
                return ResourceManager.GetString("strPlotFFTTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (Hz).
        /// </summary>
        internal static string strPlotFFTXLabel {
            get {
                return ResourceManager.GetString("strPlotFFTXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnitude (RMS²).
        /// </summary>
        internal static string strPlotFFTYLabelMag {
            get {
                return ResourceManager.GetString("strPlotFFTYLabelMag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power (dB).
        /// </summary>
        internal static string strPlotFFTYLabelPow {
            get {
                return ResourceManager.GetString("strPlotFFTYLabelPow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal dimension.
        /// </summary>
        internal static string strPlotFractalTitle {
            get {
                return ResourceManager.GetString("strPlotFractalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotFractalXLabel {
            get {
                return ResourceManager.GetString("strPlotFractalXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension (H).
        /// </summary>
        internal static string strPlotFractalYLabel {
            get {
                return ResourceManager.GetString("strPlotFractalYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input signal.
        /// </summary>
        internal static string strPlotOriginalTitle {
            get {
                return ResourceManager.GetString("strPlotOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotOriginalXLabel {
            get {
                return ResourceManager.GetString("strPlotOriginalXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        internal static string strPlotOriginalYLabel {
            get {
                return ResourceManager.GetString("strPlotOriginalYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} window.
        /// </summary>
        internal static string strPlotWindowTitle {
            get {
                return ResourceManager.GetString("strPlotWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (seconds).
        /// </summary>
        internal static string strPlotWindowXLabel {
            get {
                return ResourceManager.GetString("strPlotWindowXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        internal static string strPlotWindowYLabel {
            get {
                return ResourceManager.GetString("strPlotWindowYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current culture formatting.
        /// </summary>
        internal static string strRadCurrentCulture {
            get {
                return ResourceManager.GetString("strRadCurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant culture formatting.
        /// </summary>
        internal static string strRadInvariantCulture {
            get {
                return ResourceManager.GetString("strRadInvariantCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data points.
        /// </summary>
        internal static string strRadPoints {
            get {
                return ResourceManager.GetString("strRadPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string strRadSeconds {
            get {
                return ResourceManager.GetString("strRadSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        internal static string strRadTime {
            get {
                return ResourceManager.GetString("strRadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select culture.
        /// </summary>
        internal static string strRadUserCulture {
            get {
                return ResourceManager.GetString("strRadUserCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read data from file.
        ///{0}.
        /// </summary>
        internal static string strReadDataError {
            get {
                return ResourceManager.GetString("strReadDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid numeric value: {0}.
        /// </summary>
        internal static string strReadDataErrorNumber {
            get {
                return ResourceManager.GetString("strReadDataErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing data.
        /// </summary>
        internal static string strReadDataErrorNumberTitle {
            get {
                return ResourceManager.GetString("strReadDataErrorNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strReadDataErrorTitle {
            get {
                return ResourceManager.GetString("strReadDataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show plot&apos;s crosshair mode.
        /// </summary>
        internal static string strStatusTipCrossHair {
            get {
                return ResourceManager.GetString("strStatusTipCrossHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute the approximate and sample entropy.
        /// </summary>
        internal static string strStatusTipEntropy {
            get {
                return ResourceManager.GetString("strStatusTipEntropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute the cumulative fractal dimension (CPU intensive).
        /// </summary>
        internal static string strStatusTipFractal {
            get {
                return ResourceManager.GetString("strStatusTipFractal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot either FFT power spectra(dB) or magnitude.
        /// </summary>
        internal static string strStatusTipPower {
            get {
                return ResourceManager.GetString("strStatusTipPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        internal static string strTabGUI {
            get {
                return ResourceManager.GetString("strTabGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plotting.
        /// </summary>
        internal static string strTabPlot {
            get {
                return ResourceManager.GetString("strTabPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string strToolStripAbout {
            get {
                return ResourceManager.GetString("strToolStripAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string strToolStripExit {
            get {
                return ResourceManager.GetString("strToolStripExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string strToolStripExport {
            get {
                return ResourceManager.GetString("strToolStripExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string strToolStripOpen {
            get {
                return ResourceManager.GetString("strToolStripOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string strToolStripSettings {
            get {
                return ResourceManager.GetString("strToolStripSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this software.
        /// </summary>
        internal static string strToolTipAbout {
            get {
                return ResourceManager.GetString("strToolTipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        internal static string strToolTipExit {
            get {
                return ResourceManager.GetString("strToolTipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data and data analysis.
        /// </summary>
        internal static string strToolTipExport {
            get {
                return ResourceManager.GetString("strToolTipExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open data file from disk.
        /// </summary>
        internal static string strToolTipOpen {
            get {
                return ResourceManager.GetString("strToolTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for plots, data, and UI.
        /// </summary>
        internal static string strToolTipSettings {
            get {
                return ResourceManager.GetString("strToolTipSettings", resourceCulture);
            }
        }
    }
}
